#!/bin/sh
# Wrapper to start basex in command line mode.
#
# (c) 2011-16 Alexander Holupirek <alex@holupirek.de>, BSD
#

#DEBUG_WRAPPER=1

. /usr/lib/java-wrappers/java-wrappers.sh
find_java_runtime java7
find_jars /usr/share/java/basex.jar
# Recommended
find_jars /usr/share/java/jline2.jar
# Suggested
find_jars /usr/share/java/tagsoup.jar
find_jars /usr/share/java/xml-resolver.jar
find_jars /usr/share/java/jing.jar

run_java org.basex.BaseX "$@"
